export const contactList = [
  {
    id: "635aa6faeb08d3afc4b17897",
    index: 0,
    guid: "8a1e3397-dd70-4d1b-8b2e-ffd7d228f289",
    isActive: false,
    age: 28,
    eyeColor: "green",
    firstName: "Lawrence",
    lastName: "Ladonna",
    gender: "female",
    company: "BISBA",
    email: "ladonnalawrence@bisba.com",
    phone: "+1 (883) 533-2207",
    address: "361 Chester Avenue, Cawood, American Samoa, 388",
    about:
      "Nostrud voluptate tempor exercitation voluptate irure id. Elit commodo ipsum eu deserunt sunt mollit anim eu. Excepteur sint nisi sit fugiat excepteur consectetur sit occaecat eu quis enim est. Quis aliqua ipsum non laboris dolor culpa irure eiusmod. In non cupidatat officia occaecat eiusmod aliquip duis deserunt fugiat consectetur. Aliqua fugiat officia quis ea irure sunt nostrud labore incididunt aute. Laborum sit ex labore laboris aliqua Lorem.\r\n",
  },
  {
    id: "635aa6fa113ce70c8cf827c1",
    index: 1,
    guid: "0a8e9629-f11c-43a0-b006-66fb4ea23d01",
    isActive: true,
    age: 35,
    eyeColor: "green",
    firstName: "Sexton",
    lastName: "Haley",
    gender: "male",
    company: "IZZBY",
    email: "haleysexton@izzby.com",
    phone: "+1 (902) 519-3541",
    address: "807 Ridgecrest Terrace, Mayfair, New Mexico, 9907",
    about:
      "Ex nulla nostrud eiusmod laborum id quis ex incididunt laboris tempor adipisicing quis. Culpa ex aliqua do eiusmod labore sunt laborum cillum cillum mollit exercitation. Enim esse commodo qui id duis Lorem nostrud cupidatat dolor eu sint deserunt ullamco esse. Laborum est sit exercitation mollit pariatur non nulla ut consectetur. Velit incididunt anim pariatur laboris aliquip eu nostrud enim dolor. Labore mollit velit sint culpa consequat aliqua.\r\n",
  },
  {
    id: "635aa6fa4fdcc824bccee7ea",
    index: 2,
    guid: "0f80a0cc-1ede-424b-b4d7-261a975505fd",
    isActive: true,
    age: 20,
    eyeColor: "blue",
    firstName: "Jefferson",
    lastName: "Chambers",
    gender: "male",
    company: "MANUFACT",
    email: "chambersjefferson@manufact.com",
    phone: "+1 (863) 460-2166",
    address: "680 Strong Place, Chemung, Mississippi, 4248",
    about:
      "Voluptate laboris laboris do officia esse. Est officia pariatur laboris nisi velit amet exercitation non. Tempor in nulla quis do consequat fugiat proident eu laboris officia. Amet laborum voluptate labore in commodo consequat duis aliqua nostrud.\r\n",
  },
  {
    id: "635aa6fad1d0f1e3a59f4309",
    index: 3,
    guid: "bc1ca82b-92c1-46ac-b459-0621a3b9cfb8",
    isActive: false,
    age: 32,
    eyeColor: "brown",
    firstName: "Beasley",
    lastName: "Valeria",
    gender: "female",
    company: "ISOTRONIC",
    email: "valeriabeasley@isotronic.com",
    phone: "+1 (891) 437-3365",
    address: "714 Johnson Street, Frystown, Minnesota, 8780",
    about:
      "Excepteur irure fugiat nisi ut est exercitation voluptate velit. Amet eiusmod tempor enim adipisicing ea nostrud quis dolore pariatur nulla. Reprehenderit sunt occaecat enim laboris quis anim pariatur est ipsum mollit ea qui in.\r\n",
  },
  {
    id: "635aa6faf004c91658d0159f",
    index: 4,
    guid: "4cb18415-381c-434b-8c02-d5985b947e63",
    isActive: true,
    age: 33,
    eyeColor: "brown",
    firstName: "Roach",
    lastName: "Dale",
    gender: "male",
    company: "INTERFIND",
    email: "daleroach@interfind.com",
    phone: "+1 (840) 515-2264",
    address: "100 Division Avenue, Albrightsville, Arizona, 1250",
    about:
      "Mollit mollit qui dolor mollit magna excepteur. Veniam velit exercitation minim est proident officia et consequat sunt. Tempor duis sunt nulla consequat consequat incididunt amet.\r\n",
  },
  {
    id: "635aa6fab68b536aad2dd59f",
    index: 5,
    guid: "7ea60f16-a925-43ac-93cd-32b2d02f7f66",
    isActive: false,
    age: 37,
    eyeColor: "blue",
    firstName: "Hammond",
    lastName: "Hines",
    gender: "male",
    company: "PARAGONIA",
    email: "hineshammond@paragonia.com",
    phone: "+1 (877) 430-2669",
    address: "200 Dewey Place, Stouchsburg, Wisconsin, 9951",
    about:
      "Irure proident sit voluptate quis elit eiusmod occaecat sint. Eu exercitation aliquip aute cupidatat duis veniam amet ut non. Eu Lorem quis dolor nostrud esse tempor enim labore ad consectetur anim excepteur. Sint commodo magna deserunt dolor et exercitation fugiat laborum ipsum veniam anim in anim labore.\r\n",
  },
  {
    id: "635aa6fa70fd55dbc3b15233",
    index: 6,
    guid: "5f3c5518-9930-4347-adec-32c654795ba9",
    isActive: false,
    age: 31,
    eyeColor: "brown",
    firstName: "Green",
    lastName: "Carey",
    gender: "male",
    company: "SOLGAN",
    email: "careygreen@solgan.com",
    phone: "+1 (950) 524-3840",
    address: "682 Canarsie Road, Riegelwood, Arkansas, 7081",
    about:
      "Aliquip dolore id veniam aute reprehenderit. Minim ad officia occaecat id pariatur anim sint nulla magna eu. Id magna dolore consequat nostrud nulla nulla aliqua. Voluptate ut exercitation deserunt reprehenderit consequat laborum.\r\n",
  },
  {
    id: "635aa6fac61e7c12bb01b18d",
    index: 7,
    guid: "99755d31-a16c-4225-bc02-ae85dccd9338",
    isActive: true,
    age: 26,
    eyeColor: "brown",
    firstName: "Rodgers",
    lastName: "Dena",
    gender: "female",
    company: "NITRACYR",
    email: "denarodgers@nitracyr.com",
    phone: "+1 (907) 594-3593",
    address:
      "399 Cropsey Avenue, Clayville, Federated States Of Micronesia, 1704",
    about:
      "In pariatur id cillum voluptate nulla eu reprehenderit in elit ad in anim. Veniam exercitation Lorem excepteur consequat fugiat ullamco. Enim id occaecat cupidatat mollit labore non eu anim dolor voluptate ipsum labore. Laborum in Lorem deserunt consequat cupidatat cupidatat enim nisi cillum esse voluptate non eu.\r\n",
  },
  {
    id: "635aa6fae499a56283b56d55",
    index: 8,
    guid: "dbbf6a28-0f1d-4634-91f8-951115e7102c",
    isActive: true,
    age: 28,
    eyeColor: "green",
    firstName: "Moon",
    lastName: "Sanchez",
    gender: "male",
    company: "SUREMAX",
    email: "sanchezmoon@suremax.com",
    phone: "+1 (885) 534-2481",
    address: "728 Virginia Place, Belgreen, Oklahoma, 6391",
    about:
      "Fugiat officia eu sunt consectetur veniam aliquip officia officia minim labore esse velit Lorem. Laboris cupidatat fugiat aliqua consectetur minim anim consectetur et reprehenderit culpa cupidatat quis. Ad cillum proident labore aliquip. Aliqua dolor irure proident esse. Esse aliqua in amet velit magna dolor irure commodo velit in excepteur pariatur.\r\n",
  },
  {
    id: "635aa6fa2d1e893b0702d288",
    index: 9,
    guid: "f7fbf6b0-555e-4ace-8c66-a24f2c150f1d",
    isActive: false,
    age: 28,
    eyeColor: "blue",
    firstName: "Cherry",
    lastName: "Doris",
    gender: "female",
    company: "FIREWAX",
    email: "dorischerry@firewax.com",
    phone: "+1 (856) 507-3786",
    address: "198 Lawn Court, Fannett, Nebraska, 3187",
    about:
      "Id anim veniam officia ut irure. Enim proident cupidatat proident anim deserunt nulla officia occaecat non laborum laborum eiusmod. Nulla ea ea excepteur qui ipsum eiusmod ea reprehenderit fugiat.\r\n",
  },
  {
    id: "635aa6fa0c879d371c2ca11c",
    index: 10,
    guid: "d35efc3c-8a73-4ec3-b1b7-e46a387856fe",
    isActive: false,
    age: 25,
    eyeColor: "blue",
    firstName: "Pitts",
    lastName: "Bessie",
    gender: "female",
    company: "CEMENTION",
    email: "bessiepitts@cemention.com",
    phone: "+1 (958) 539-3408",
    address: "262 Ash Street, Nogal, Louisiana, 5875",
    about:
      "Culpa eu sunt veniam dolore aute id ipsum incididunt. Esse aute duis magna consectetur reprehenderit irure officia nulla. Occaecat incididunt nulla reprehenderit sint sunt dolor aliqua irure laborum pariatur laborum. Deserunt ad do enim exercitation culpa laboris laboris commodo sunt. Aliqua nulla ex aliquip nulla exercitation laborum labore enim sit ullamco duis ipsum ex. Mollit cupidatat ullamco culpa exercitation aute. Amet sunt aliquip laborum quis sint mollit consequat sunt esse commodo ullamco fugiat do minim.\r\n",
  },
  {
    id: "635aa6fa8ed8ff4df8b0b171",
    index: 11,
    guid: "d1b6cdd0-f1b7-49ff-b498-041c0c74be76",
    isActive: false,
    age: 35,
    eyeColor: "blue",
    firstName: "Sutton",
    lastName: "Chrystal",
    gender: "female",
    company: "VENOFLEX",
    email: "chrystalsutton@venoflex.com",
    phone: "+1 (984) 555-3265",
    address: "871 Conselyea Street, Saranap, West Virginia, 8297",
    about:
      "Consectetur aute proident laborum magna voluptate duis mollit qui eiusmod magna occaecat. Voluptate aliquip consectetur ad esse sint dolore aliquip deserunt cillum Lorem quis id aliquip laboris. Sint mollit sit eu aliqua nisi esse eiusmod minim elit consectetur occaecat. Est in voluptate adipisicing tempor aliqua minim laboris in culpa quis sit. Aliqua enim magna anim ea quis labore labore nostrud consectetur proident.\r\n",
  },
  {
    id: "635aa6fa94673ff7116e8c4e",
    index: 12,
    guid: "ddfebec1-9aa4-4084-9b58-e55e9231fe86",
    isActive: false,
    age: 22,
    eyeColor: "green",
    firstName: "Parsons",
    lastName: "Bridgette",
    gender: "female",
    company: "ORBOID",
    email: "bridgetteparsons@orboid.com",
    phone: "+1 (821) 453-2502",
    address: "912 Lincoln Avenue, Cucumber, Alabama, 9809",
    about:
      "Sint do adipisicing sunt esse consectetur culpa adipisicing labore eu nulla occaecat id esse. Laborum minim culpa irure ea veniam elit esse. Et est reprehenderit magna voluptate officia dolore labore ex deserunt amet. Anim minim qui tempor aute sint. Sit dolore pariatur minim laboris in aute magna eu occaecat sint consequat. Nostrud ullamco anim fugiat laborum tempor elit.\r\n",
  },
  {
    id: "635aa6fac9a971a4552b5a7f",
    index: 13,
    guid: "2739ada7-6331-4cd3-9fa7-db0ec73cba00",
    isActive: true,
    age: 32,
    eyeColor: "green",
    firstName: "Jacobson",
    lastName: "Johnson",
    gender: "male",
    company: "ISOLOGIX",
    email: "johnsonjacobson@isologix.com",
    phone: "+1 (838) 535-2921",
    address: "541 Eldert Lane, Boomer, Washington, 2573",
    about:
      "Non nostrud elit reprehenderit fugiat commodo et non ut reprehenderit in. Ex eiusmod magna id et ut enim. Nostrud do sunt ad minim ullamco mollit ad ex veniam ut Lorem deserunt in.\r\n",
  },
  {
    id: "635aa6fa26c79fd21f331bc2",
    index: 14,
    guid: "658bbca3-3f71-492f-97ac-b770ba690126",
    isActive: true,
    age: 39,
    eyeColor: "blue",
    firstName: "Kaufman",
    lastName: "Carey",
    gender: "female",
    company: "ISOPOP",
    email: "careykaufman@isopop.com",
    phone: "+1 (889) 544-3930",
    address: "292 Bristol Street, Drummond, South Carolina, 5747",
    about:
      "Ullamco qui ex aliquip Lorem. Aliquip Lorem enim esse cupidatat voluptate qui pariatur ex qui veniam culpa. Labore irure sint commodo anim deserunt dolore nisi. Ex est velit labore amet commodo nulla laboris veniam Lorem velit incididunt dolore nisi laboris. Reprehenderit cupidatat velit ullamco eiusmod deserunt aliqua eu ullamco aute sunt. Deserunt aute duis fugiat sit ut cupidatat. Culpa ullamco est cillum in adipisicing ut reprehenderit culpa id irure velit Lorem amet dolore.\r\n",
  },
  {
    id: "635aa6facd3be142c63e30ad",
    index: 15,
    guid: "14cd8f9f-6c0d-4efd-9061-bda69c544c24",
    isActive: true,
    age: 27,
    eyeColor: "blue",
    firstName: "Henry",
    lastName: "Marie",
    gender: "female",
    company: "ENERSOL",
    email: "mariehenry@enersol.com",
    phone: "+1 (834) 559-3417",
    address: "730 Coleridge Street, Maxville, Puerto Rico, 2969",
    about:
      "Magna anim sit consequat ullamco aliquip officia. Elit deserunt ullamco id irure quis sint. Ad veniam et eiusmod velit culpa voluptate.\r\n",
  },
  {
    id: "635aa6fad753471f1e787cf6",
    index: 16,
    guid: "002e77ad-4f5b-4899-8f7a-363b7a7486ba",
    isActive: false,
    age: 35,
    eyeColor: "green",
    firstName: "Bishop",
    lastName: "Collier",
    gender: "male",
    company: "GLUKGLUK",
    email: "collierbishop@glukgluk.com",
    phone: "+1 (994) 582-3412",
    address: "204 Victor Road, Sisquoc, Texas, 8866",
    about:
      "Aliqua excepteur ipsum minim adipisicing voluptate tempor amet laboris enim sunt tempor. Cupidatat laborum adipisicing tempor magna labore nulla tempor ad et occaecat do quis est Lorem. Reprehenderit mollit et pariatur veniam irure et esse. Tempor ipsum ipsum incididunt consequat adipisicing cillum officia ea dolor.\r\n",
  },
  {
    id: "635aa6fa2bcfb6dca831d7fd",
    index: 17,
    guid: "f431cc1c-35d6-463c-8fcc-36783d43006d",
    isActive: true,
    age: 30,
    eyeColor: "brown",
    firstName: "Macias",
    lastName: "Bush",
    gender: "male",
    company: "GEEKETRON",
    email: "bushmacias@geeketron.com",
    phone: "+1 (983) 534-3991",
    address: "866 Hyman Court, Canby, North Carolina, 8176",
    about:
      "Excepteur ad eiusmod amet non et pariatur. Esse non anim eu culpa deserunt cupidatat. Irure veniam excepteur elit quis aute mollit. Lorem do culpa commodo magna. Minim deserunt dolor labore mollit proident. Est sit est aliqua sunt nostrud consectetur labore. Fugiat officia proident nulla amet cillum eiusmod ut non non ad eiusmod sunt.\r\n",
  },
  {
    id: "635aa6fa9902265f945d7180",
    index: 18,
    guid: "7cd5078b-dfab-4160-9e3e-1d6202cd7135",
    isActive: false,
    age: 30,
    eyeColor: "blue",
    firstName: "Travis",
    lastName: "Powell",
    gender: "male",
    company: "DIGIGEN",
    email: "powelltravis@digigen.com",
    phone: "+1 (975) 516-2632",
    address: "639 Llama Court, Cassel, Michigan, 7791",
    about:
      "In ex pariatur cillum nulla anim sint velit veniam pariatur sunt irure non occaecat sit. Ullamco exercitation occaecat velit labore veniam quis mollit Lorem duis. Excepteur sunt amet sit dolore officia aliqua et anim ea ea. Do velit eu laboris enim incididunt tempor sunt aliqua dolor voluptate dolore eiusmod enim ullamco. Sint sit ea adipisicing aute elit officia est sint.\r\n",
  },
  {
    id: "635aa6faf1fe79ad6f426d05",
    index: 19,
    guid: "2fd9bb07-1f39-4f19-9870-5afe5c18f281",
    isActive: true,
    age: 24,
    eyeColor: "green",
    firstName: "King",
    lastName: "Lola",
    gender: "female",
    company: "CAXT",
    email: "lolaking@caxt.com",
    phone: "+1 (834) 566-2170",
    address: "332 Fayette Street, Knowlton, District Of Columbia, 3397",
    about:
      "Lorem adipisicing aliquip fugiat dolore anim exercitation ex minim sunt magna sunt Lorem esse. Cupidatat reprehenderit magna occaecat dolore magna amet esse cupidatat cillum labore sunt amet. Enim irure laborum ex pariatur adipisicing proident irure sint anim Lorem eu. In officia ad aliqua commodo culpa veniam nisi. Tempor ad nisi anim non aliquip ullamco dolor deserunt velit ullamco.\r\n",
  },
  {
    id: "635aa6faa22a41bbcb1ae5ff",
    index: 20,
    guid: "f31eb79e-5643-470a-8f81-c2dfb202b857",
    isActive: false,
    age: 30,
    eyeColor: "blue",
    firstName: "Mccullough",
    lastName: "Avis",
    gender: "female",
    company: "ZOXY",
    email: "avismccullough@zoxy.com",
    phone: "+1 (875) 548-2815",
    address: "494 Maujer Street, Chapin, Missouri, 5834",
    about:
      "Aute id sint mollit fugiat. Enim cupidatat est ipsum pariatur ad voluptate officia sit. Id et ullamco ullamco consequat nulla irure. Elit esse ex velit esse sit et ipsum nulla exercitation sunt irure excepteur officia. Est incididunt laborum sint laboris adipisicing labore occaecat aliqua elit. Nostrud eu est magna fugiat quis et.\r\n",
  },
  {
    id: "635aa6fa07be089a91473ec8",
    index: 21,
    guid: "a5f80859-52c1-4a9d-ae79-dc0e8ebbef07",
    isActive: false,
    age: 37,
    eyeColor: "blue",
    firstName: "Hurley",
    lastName: "Dale",
    gender: "female",
    company: "MARTGO",
    email: "dalehurley@martgo.com",
    phone: "+1 (929) 468-3172",
    address: "810 Herkimer Court, Hasty, New Hampshire, 2966",
    about:
      "Veniam culpa velit amet ipsum adipisicing eiusmod dolor ea. Cillum non aliquip excepteur laborum reprehenderit voluptate mollit ad veniam anim. Est elit commodo cillum incididunt ipsum nostrud ipsum ipsum aliqua. Occaecat pariatur do enim dolore nisi reprehenderit nulla aliquip ex. Proident exercitation aliquip duis nostrud laborum magna nisi dolor nulla nisi laborum enim laborum. Eu fugiat nulla voluptate ut laborum excepteur. Dolor proident velit sint pariatur dolor anim sint excepteur elit anim elit reprehenderit.\r\n",
  },
];
